WIP on browser bundle: Add UMD build via Rollup.
This loads in the browser, but with an error along the way:

    TypeError: stream is undefined

This is likely because none of the other dependencies are available.